In [2]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 89, -61,  57,  34,   1,   2])

In [3]:
tensor = torch.tensor([[0.1, 1.1], [0.2, 2], [5.1, 8.1]])
tensor

tensor([[0.1000, 1.1000],
        [0.2000, 2.0000],
        [5.1000, 8.1000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
inputs = torch.empty(2, 3)
inputs

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
a = torch.rand(2, 3)
print(a)
x, y = a.shape
a = a.view(x, y)
a

tensor([[0.8313, 0.2665, 0.8741],
        [0.9653, 0.8959, 0.4525]])


tensor([[0.8313, 0.2665, 0.8741],
        [0.9653, 0.8959, 0.4525]])