In [7]:
import torch
from torch.nn import functional as F

AttributeError: partially initialized module 'torch' from 'd:\LLM\cuda_env\Lib\site-packages\torch\__init__.py' has no attribute 'types' (most likely due to a circular import)

In [8]:
import torch
randint = torch.randint(-100, 100, (6,))
randint

AttributeError: partially initialized module 'torch' from 'd:\LLM\cuda_env\Lib\site-packages\torch\__init__.py' has no attribute 'types' (most likely due to a circular import)

In [3]:
tensor = torch.tensor([[0.1, 1.1], [0.2, 2], [5.1, 8.1]])
tensor

tensor([[0.1000, 1.1000],
        [0.2000, 2.0000],
        [5.1000, 8.1000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
inputs = torch.empty(2, 3)
inputs

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
a = torch.rand(2, 3)
print(a)
x, y = a.shape
a = a.view(x, y)
a

tensor([[0.8313, 0.2665, 0.8741],
        [0.9653, 0.8959, 0.4525]])


tensor([[0.8313, 0.2665, 0.8741],
        [0.9653, 0.8959, 0.4525]])

In [3]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)
print(y)

RuntimeError: storage_module && PyModule_Check(storage_module) INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\pytorch\\torch\\csrc\\DynamicTypes.cpp":71, please report a bug to PyTorch. 